# Generated by Django 5.0.6 on 2026-04-25 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_updates', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fields.field')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', '-created_at'], name='updates_fie_field_i_c4953f_idx')],
            },
        ),
    ]
